### ISSUE TITLE
NullPointerException in ServerSocketThread at line 64

### ISSUE THREAD

**Issue by itsyogesh** [dteviot/epubWorkspace#1]
There was a null pointerException in ServerSocketThread.java which led to force closing of app when loading the ebook in Landscape mode. It was caused by mServerSocket.close() at line 64. 

I added my solution, like this..
try {
            // force thread out of accept().
            if(mServerSocket!=null)
            mServerSocket.close();
        } catch (IOException e) {
            // Ignore any error, nothing to do
        }
So just an if statement, but it now works really great.

P.S. Thanks for the tutorial.

**Comment by dteviot** [comment]
Thanks.  I suspect you're actually looking at a race condition, and the correct way to fix this is use NIO socket communications.  I may look into it in the future, when I have some spare time.  What version of Andriod were you running?

**Comment by itsyogesh** [comment]
I am using android 4.3. Just asking, how do I implement NIO.

**Comment by dteviot** [comment]
http://stackoverflow.com/questions/8940747/how-should-i-use-asynchronousserversocketchannel-for-accepting-connections

Looking at code, it IS a race condition.
Assumed order of events is:
1. Program starts
2. MainActivity Constructs ServerSocketThread
3. Main thread calls ServerSocketThread.startThread().  This will create a worker thread that will (at some stage) call run() and create the ServerSocket.
4. MainActivity.onDestroy() is called as part of changing from Portrait to Landscape.  This calls ServerSocketThread.stopThread() which tries to close the ServerSocket.

However under a race condition,
event 4 occurs before event 3.  So, ServerSocket hasn't been created yet.
Thus, simplest fix may be to create the ServerSocket in ServerSocketThread's constructor.
i.e. Move this line:
            mServerSocket = new ServerSocket(mPort);
from ServerSocketThread.run() into ServerSocketThread's constructor.

Note, this may not work.  I'm not sure what the rules are regarding moving sockets between threads. (I know Windows doesn't like it.)  That said, Oracle's documentation on ServerSocket don't say anything.
I'm currently at work, so can't try this out myself.

**Comment by dteviot** [comment]
Closed by mistake.

**Comment by dteviot** [comment]
Moving ServerSocket's creation to ServerSocketThread stops race.
Fix is in commit 72fbb93b4b.
