### ISSUE TITLE
Feature: How do I implement pagination inside the chapters.

### ISSUE THREAD

**Issue by itsyogesh** [dteviot/epubWorkspace#2]
Hey,

I was working on a couple of ePub readers trying to implement the pagination technique. I was wondering how can I implement that in epubWorkspace. There are a couple of open source epub readers built for android, I looked at Pageturner (https://github.com/NightWhistler/PageTurner) but couldn't make out much. Do you have any ideas on how to do it.

Thanks,
Yogesh

**Comment by dteviot** [comment]
http://www.codeproject.com/Articles/592909/EPUB-Viewer-for-Android-with-Text-to-Speech?msg=4722176#xx4722176xx
