### ISSUE TITLE
How add javascript file to <head> tag

### ISSUE THREAD

**Issue by masoud-c** [dteviot/epubWorkspace#4]
i need to add some javascript like:

```
     <script src='file:///android_asset/jquery-1.8.3.js'></script>
```

to the main content for selection,
how can i do it?

**Comment by dteviot** [comment]
I suggest you read the CodeProject article http://www.codeproject.com/Articles/592909/EPUB-Viewer-for-Android-with-Text-to-Speech I wrote. I the section "Viewing the Content on Android 2.3 (and below)" I detail how to use and XML filter pipeline to convert the XML on the fly.  Modifying the <head> tag to include a <script> element is the same technique.

That said, you're also going to have to modify url2ResourceName() to recognise when the script is being requested.

My final thought is "what is your reason for adding the script"?  What are you trying to achieve?

**Comment by masoud-c** [comment]
thanks... i solved it by using this - > http://stackoverflow.com/a/21612566/2555951 solution
