### ISSUE TITLE
Can you add license copy with project. (Suggestion)

### ISSUE THREAD

**Issue by premchand-algo** [dteviot/epubWorkspace#7]
Hi,

I am using this for help in my project. But their requirement of license copy with it by company to use it. Can you add Apache License, Version 2.0  with it?
.

**Comment by dteviot** [comment]
@premchand-algo 

I can't change the license on GitHub from COPL,
However, I hereby grant you rights to the code under the terms of an Apache License Version 2.0.
Does that work for you?

**Comment by premchand-algo** [comment]
@dteviot 

Thank you, 
It's fine to grant me rights to the code under the terms of an Apache License Version 2.0.
Just I want to know that, Can I modify your code as my requirements and use for commercial purpose?

**Comment by dteviot** [comment]
@premchand-algo

That IS what Apache grants you, so yes.
It was also allowed under COPL as well.
